# Generated by Django 5.1.2 on 2024-10-15 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название игры')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр игры')),
                ('platform', models.CharField(max_length=100, verbose_name='Платформа')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название турнира')),
                ('description', models.TextField(blank=True, verbose_name='Описание турнира')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала турнира')),
                ('end_date', models.DateTimeField(verbose_name='Дата и время окончания турнира')),
                ('location', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='users.game', verbose_name='Игра')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('tournaments', models.ManyToManyField(related_name='teams', to='users.tournament', verbose_name='Турниры')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.IntegerField(default=0, verbose_name='Счет команды A')),
                ('score_b', models.IntegerField(default=0, verbose_name='Счет команды B')),
                ('match_date', models.DateTimeField(verbose_name='Дата и время матча')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='users.team', verbose_name='Команда A')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='users.team', verbose_name='Команда B')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='users.tournament', verbose_name='Турнир')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название лиги')),
                ('tournaments', models.ManyToManyField(related_name='leagues', to='users.tournament', verbose_name='Турниры')),
            ],
        ),
    ]
